#! /bin/sh
#===========================================================================
#
#
#███╗   ███╗ █████╗ ██████╗ ██╗ ██████╗ ██████╗ ██████╗  ██████╗ ███╗   ███╗
#████╗ ████║██╔══██╗██╔══██╗██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗████╗ ████║
#██╔████╔██║███████║██████╔╝██║██║   ██║██████╔╝██████╔╝██║   ██║██╔████╔██║
#██║╚██╔╝██║██╔══██║██╔══██╗██║██║   ██║██╔══██╗██╔══██╗██║   ██║██║╚██╔╝██║
#██║ ╚═╝ ██║██║  ██║██║  ██║██║╚██████╔╝██║  ██║██║  ██║╚██████╔╝██║ ╚═╝ ██║
#╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═╝ ╚═╝ ╚═════╝ ╚═╝     ╚═╝                                                                          
#                          MarioRRom's Dotfiles
#                 https://github.com/MarioRRom/bspwm-dotfiles
#===========================================================================


## Cargar los ajustes de Monitor
## Puedes crear este archivo usando arandr
~/.screenlayout/screenlayout.sh
sleep 1

#  .-------------------------.
#  | .---------------------. |
#  | | Variables de Entono | |
#  | `---------------------' |
#  `-------------------------'

export XDG_CURRENT_DESKTOP='bspwm'
export _JAVA_AWT_WM_NONREPARENTING=1
export LC_TIME="en_US.UTF-8"
BSPDIR="$HOME/.config/bspwm"
PATH="$BSPDIR/scripts:$PATH"


#  .-------------------------.
#  | .---------------------. |
#  | |     Workspaces      | |
#  | `---------------------' |
#  `-------------------------'

workspaces() {
    name=1
    for monitor in $(bspc query -M); do
        bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6'
        ((name++))
    done
}

workspaces


#  .-------------------------.
#  | .---------------------. |
#  | |    Decoraciones     | |
#  | `---------------------' |
#  `-------------------------'
bsp_borwidth=$(Config-Editor --leer bsp_borwidth)
bspc config border_width         "$bsp_borwidth"

bspc config active_border_color "#45475a"
bspc config focused_border_color "#89dceb"

bsp_wingap=$(Config-Editor --leer bsp_wingap)
bspc config window_gap          "$bsp_wingap"

bspc config split_ratio          0.52
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false


#  .-------------------------.
#  | .---------------------. |
#  | |Configuarion de Mouse| |
#  | `---------------------' |
#  `-------------------------'

bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
xsetroot -cursor_name left_ptr &


#  .-------------------------.
#  | .---------------------. |
#  | | Reglas de Ventanas  | |
#  | `---------------------' |
#  `-------------------------'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating


#  .-------------------------.
#  | .---------------------. |
#  | | Leer Configuraciones| |
#  | `---------------------' |
#  `-------------------------'

## Establecer distribucion de Teclado
keyboard_layout=$(Config-Editor --leer keyboard)

if [[ -n "$keyboard_layout" ]]; then
    setxkbmap "$keyboard_layout"
fi

## Establecer el Fondo de Pantalla
SetWallpaper &


#  .-------------------------.
#  | .---------------------. |
#  | |Procesos al Arrancar | |
#  | `---------------------' |
#  `-------------------------'


## Matar todos los procesos al Reiniciar
processes=("picom" "polybar" "eww" "sxhkd" "dunst" "xsettingsd")

for process in "${processes[@]}"; do
  if pidof -q "$process"; then
    pkill -9 -x "$process" > /dev/null; sleep 0.1
  fi
done


## Lanzar el gestor de atajos de Teclado
sxhkd -c "$BSPDIR"/config/keys &


## Lanzar el Compositor picom
picom --config "$BSPDIR"/config/picom/picom.conf & 


## Lanzar polybar en cada monitor
if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
        MONITOR=$m polybar --reload -c "$BSPDIR"/config/polybar/top_bar.ini &
    done
else
    polybar --reload -c "$BSPDIR"/config/polybar/top_bar.ini &
fi


## Lanzar Eww
Eww daemon &


## Lanzar dunst para las notificaciones
dunst -config "$BSPDIR"/config/notificaciones &


## Iniciar Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


#cargar el Xresources
xrdb -merge "$HOME"/.Xresources &


#Xsettingsd
xsettingsd --config="$BSPDIR"/config/xsettingsd &

# Lanzar los programas comprendidos en  ~/.config/autostart/
Autostart &


#  .-------------------------.
#  | .---------------------. |
#  | |Soporte para Widgets | |
#  | `---------------------' |
#  `-------------------------'

# Contador de Actualizaciones
if pgrep -x "Updates-Counter" > /dev/null; then
    killall "Updates-Counter"
fi
Updates-Counter &

# Obtener el Clima
if pgrep -x "Weather-Updater" > /dev/null; then
    killall "Weather-Updater"
fi
Weather-Updater &